// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Live clock state from the Erlang session-manager. Null for games that have no
// live session (games against the engine).
type Clock struct {
	WhiteMs int `json:"whiteMs"`
	BlackMs int `json:"blackMs"`
	// Side whose clock is currently running.
	Turn Side `json:"turn"`
	// False once the session has finished.
	Running bool `json:"running"`
}

type CreateGameInput struct {
	// Play Stockfish. When false the game waits for an opponent to join.
	VsEngine *bool `json:"vsEngine,omitempty"`
	// Invite a specific opponent. Omit to leave the seat open to anyone.
	BlackID *string `json:"blackId,omitempty"`
	// Engine search depth for replies; 0 uses the worker default.
	EngineDepth *int `json:"engineDepth,omitempty"`
	// Time control for live sessions; 0 uses the session-manager defaults.
	InitialMs   *int `json:"initialMs,omitempty"`
	IncrementMs *int `json:"incrementMs,omitempty"`
	// Rated games move both players' Elo on completion. Ignored for engine games.
	Rated *bool `json:"rated,omitempty"`
}

type Game struct {
	ID string `json:"id"`
	// Current position in FEN.
	Fen       string     `json:"fen"`
	Status    GameStatus `json:"status"`
	EndReason *EndReason `json:"endReason,omitempty"`
	VsEngine  bool       `json:"vsEngine"`
	// True while a human game is still waiting for an opponent to join.
	AwaitingOpponent bool `json:"awaitingOpponent"`
	// True when the result will move both players' Elo.
	Rated   bool   `json:"rated"`
	WhiteID string `json:"whiteId"`
	// Null when playing the engine, or until an opponent joins.
	BlackID   *string    `json:"blackId,omitempty"`
	Moves     []*Move    `json:"moves"`
	StartedAt time.Time  `json:"startedAt"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
	// Live session state; resolved from the session-manager on demand.
	Clock *Clock `json:"clock,omitempty"`
}

type GameHistory struct {
	Games []*GameSummary `json:"games"`
	Total int            `json:"total"`
}

// A finished or ongoing game, summarised for history lists.
type GameSummary struct {
	ID        string     `json:"id"`
	WhiteID   string     `json:"whiteId"`
	WhiteName string     `json:"whiteName"`
	BlackID   *string    `json:"blackId,omitempty"`
	BlackName string     `json:"blackName"`
	VsEngine  bool       `json:"vsEngine"`
	Rated     bool       `json:"rated"`
	Status    GameStatus `json:"status"`
	EndReason *EndReason `json:"endReason,omitempty"`
	MoveCount int        `json:"moveCount"`
	// Your rating change for this game; null when unrated or not yet scored.
	EloDelta  *int       `json:"eloDelta,omitempty"`
	StartedAt time.Time  `json:"startedAt"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
}

type LeaderboardEntry struct {
	Rank        int    `json:"rank"`
	UserID      string `json:"userId"`
	Username    string `json:"username"`
	Elo         int    `json:"elo"`
	GamesPlayed int    `json:"gamesPlayed"`
}

type LoginInput struct {
	// Username or email — either works.
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

// Issued when requesting a passwordless sign-in link.
type LoginTokenRequest struct {
	// The one-time token, returned only when no mail provider is configured (local
	// development). In production this is null and the token is emailed.
	Token     *string    `json:"token,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// True when the token was returned here instead of being emailed.
	DeliveredInBand bool `json:"deliveredInBand"`
}

// A single half-move.
type Move struct {
	// Half-move number, starting at 1.
	Ply int `json:"ply"`
	// Move in UCI long algebraic notation, e.g. "e2e4".
	Uci string `json:"uci"`
	// Resulting position in FEN.
	FenAfter string `json:"fenAfter"`
}

type MoveInput struct {
	GameID string `json:"gameId"`
	// Move in UCI long algebraic notation.
	Uci string `json:"uci"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	// Optional, but required later for passwordless sign-in.
	Email *string `json:"email,omitempty"`
	// Upgrade your current guest account instead of creating a new one, so games and
	// rating earned before signing up are kept.
	UpgradeCurrentGuest *bool `json:"upgradeCurrentGuest,omitempty"`
}

type ResignInput struct {
	GameID string `json:"gameId"`
}

// The result of signing in. The session is also set as an httpOnly cookie, which
// is what the web client relies on; `token` is returned for non-browser clients
// that cannot hold cookies.
type Session struct {
	User      *User     `json:"user"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Subscription struct {
}

// A player account. Guests are real accounts with no credentials attached.
type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	// Only present on your own account.
	Email       *string   `json:"email,omitempty"`
	Elo         int       `json:"elo"`
	IsGuest     bool      `json:"isGuest"`
	GamesPlayed int       `json:"gamesPlayed"`
	CreatedAt   time.Time `json:"createdAt"`
}

// Why a finished game ended.
type EndReason string

const (
	EndReasonCheckmate            EndReason = "CHECKMATE"
	EndReasonStalemate            EndReason = "STALEMATE"
	EndReasonInsufficientMaterial EndReason = "INSUFFICIENT_MATERIAL"
	EndReasonFiftyMove            EndReason = "FIFTY_MOVE"
	EndReasonThreefold            EndReason = "THREEFOLD"
	EndReasonResignation          EndReason = "RESIGNATION"
	EndReasonFlag                 EndReason = "FLAG"
	EndReasonAbandonment          EndReason = "ABANDONMENT"
)

var AllEndReason = []EndReason{
	EndReasonCheckmate,
	EndReasonStalemate,
	EndReasonInsufficientMaterial,
	EndReasonFiftyMove,
	EndReasonThreefold,
	EndReasonResignation,
	EndReasonFlag,
	EndReasonAbandonment,
}

func (e EndReason) IsValid() bool {
	switch e {
	case EndReasonCheckmate, EndReasonStalemate, EndReasonInsufficientMaterial, EndReasonFiftyMove, EndReasonThreefold, EndReasonResignation, EndReasonFlag, EndReasonAbandonment:
		return true
	}
	return false
}

func (e EndReason) String() string {
	return string(e)
}

func (e *EndReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EndReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EndReason", str)
	}
	return nil
}

func (e EndReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EndReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EndReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Lifecycle state / result of a game.
type GameStatus string

const (
	GameStatusInProgress GameStatus = "IN_PROGRESS"
	GameStatusWhiteWon   GameStatus = "WHITE_WON"
	GameStatusBlackWon   GameStatus = "BLACK_WON"
	GameStatusDraw       GameStatus = "DRAW"
)

var AllGameStatus = []GameStatus{
	GameStatusInProgress,
	GameStatusWhiteWon,
	GameStatusBlackWon,
	GameStatusDraw,
}

func (e GameStatus) IsValid() bool {
	switch e {
	case GameStatusInProgress, GameStatusWhiteWon, GameStatusBlackWon, GameStatusDraw:
		return true
	}
	return false
}

func (e GameStatus) String() string {
	return string(e)
}

func (e *GameStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GameStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GameStatus", str)
	}
	return nil
}

func (e GameStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GameStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GameStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Which side of the board.
type Side string

const (
	SideWhite Side = "WHITE"
	SideBlack Side = "BLACK"
)

var AllSide = []Side{
	SideWhite,
	SideBlack,
}

func (e Side) IsValid() bool {
	switch e {
	case SideWhite, SideBlack:
		return true
	}
	return false
}

func (e Side) String() string {
	return string(e)
}

func (e *Side) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Side(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Side", str)
	}
	return nil
}

func (e Side) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Side) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Side) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
