version: "2"
linters:
  enable:
    - bodyclose
    - misspell
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - proto/gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/IshaanNene/AlekhinesCounter-Gambit
  exclusions:
    generated: lax
    paths:
      - proto/gen
      - third_party$
      - builtin$
      - examples$
