%% -*- coding: utf-8 -*-
%% @private
%% Automatically @generated, do not edit
%% Generated by gpb_compile version 4.21.7
%% Version source: file
-module(session_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_alekhine.session.v1.Side'/1, 'enum_value_by_symbol_alekhine.session.v1.Side'/1]).
-export(['enum_symbol_by_value_alekhine.session.v1.SessionStatus'/1, 'enum_value_by_symbol_alekhine.session.v1.SessionStatus'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types
-type 'alekhine.session.v1.Side'() :: 'SIDE_UNSPECIFIED' | 'SIDE_WHITE' | 'SIDE_BLACK'.
-type 'alekhine.session.v1.SessionStatus'() :: 'SESSION_STATUS_UNSPECIFIED' | 'SESSION_STATUS_IN_PROGRESS' | 'SESSION_STATUS_FINISHED'.
-export_type(['alekhine.session.v1.Side'/0, 'alekhine.session.v1.SessionStatus'/0]).

%% message types
-type create_session_request() ::
      #{game_id                 => unicode:chardata(), % = 1, optional
        white_id                => unicode:chardata(), % = 2, optional
        black_id                => unicode:chardata(), % = 3, optional
        initial_ms              => integer(),       % = 4, optional, 64 bits
        increment_ms            => integer(),       % = 5, optional, 64 bits
        grace_ms                => integer()        % = 6, optional, 64 bits
       }.

-type player_ref() ::
      #{game_id                 => unicode:chardata(), % = 1, optional
        player_id               => unicode:chardata() % = 2, optional
       }.

-type game_ref() ::
      #{game_id                 => unicode:chardata() % = 1, optional
       }.

-type end_session_request() ::
      #{game_id                 => unicode:chardata(), % = 1, optional
        winner                  => 'SIDE_UNSPECIFIED' | 'SIDE_WHITE' | 'SIDE_BLACK' | integer(), % = 2, optional, enum alekhine.session.v1.Side
        reason                  => unicode:chardata() % = 3, optional
       }.

-type snapshot() ::
      #{game_id                 => unicode:chardata(), % = 1, optional
        status                  => 'SESSION_STATUS_UNSPECIFIED' | 'SESSION_STATUS_IN_PROGRESS' | 'SESSION_STATUS_FINISHED' | integer(), % = 2, optional, enum alekhine.session.v1.SessionStatus
        turn                    => 'SIDE_UNSPECIFIED' | 'SIDE_WHITE' | 'SIDE_BLACK' | integer(), % = 3, optional, enum alekhine.session.v1.Side
        white_ms                => integer(),       % = 4, optional, 64 bits
        black_ms                => integer(),       % = 5, optional, 64 bits
        winner                  => 'SIDE_UNSPECIFIED' | 'SIDE_WHITE' | 'SIDE_BLACK' | integer(), % = 6, optional, enum alekhine.session.v1.Side
        reason                  => unicode:chardata(), % = 7, optional
        spectators              => [unicode:chardata()], % = 8, repeated
        error                   => unicode:chardata() % = 9, optional
       }.

-export_type(['create_session_request'/0, 'player_ref'/0, 'game_ref'/0, 'end_session_request'/0, 'snapshot'/0]).
-type '$msg_name'() :: create_session_request | player_ref | game_ref | end_session_request | snapshot.
-type '$msg'() :: create_session_request() | player_ref() | game_ref() | end_session_request() | snapshot().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_session_request -> encode_msg_create_session_request(id(Msg, TrUserData), TrUserData);
        player_ref -> encode_msg_player_ref(id(Msg, TrUserData), TrUserData);
        game_ref -> encode_msg_game_ref(id(Msg, TrUserData), TrUserData);
        end_session_request -> encode_msg_end_session_request(id(Msg, TrUserData), TrUserData);
        snapshot -> encode_msg_snapshot(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_create_session_request(Msg, TrUserData) -> encode_msg_create_session_request(Msg, <<>>, TrUserData).


encode_msg_create_session_request(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{game_id := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{white_id := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     case is_empty_string(TrF2) of
                         true -> B1;
                         false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{black_id := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     case is_empty_string(TrF3) of
                         true -> B2;
                         false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    B4 = case M of
             #{initial_ms := F4} ->
                 begin
                     TrF4 = id(F4, TrUserData),
                     if TrF4 =:= 0 -> B3;
                        true -> e_type_int64(TrF4, <<B3/binary, 32>>, TrUserData)
                     end
                 end;
             _ -> B3
         end,
    B5 = case M of
             #{increment_ms := F5} ->
                 begin
                     TrF5 = id(F5, TrUserData),
                     if TrF5 =:= 0 -> B4;
                        true -> e_type_int64(TrF5, <<B4/binary, 40>>, TrUserData)
                     end
                 end;
             _ -> B4
         end,
    case M of
        #{grace_ms := F6} ->
            begin
                TrF6 = id(F6, TrUserData),
                if TrF6 =:= 0 -> B5;
                   true -> e_type_int64(TrF6, <<B5/binary, 48>>, TrUserData)
                end
            end;
        _ -> B5
    end.

encode_msg_player_ref(Msg, TrUserData) -> encode_msg_player_ref(Msg, <<>>, TrUserData).


encode_msg_player_ref(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{game_id := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    case M of
        #{player_id := F2} ->
            begin
                TrF2 = id(F2, TrUserData),
                case is_empty_string(TrF2) of
                    true -> B1;
                    false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                end
            end;
        _ -> B1
    end.

encode_msg_game_ref(Msg, TrUserData) -> encode_msg_game_ref(Msg, <<>>, TrUserData).


encode_msg_game_ref(#{} = M, Bin, TrUserData) ->
    case M of
        #{game_id := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                case is_empty_string(TrF1) of
                    true -> Bin;
                    false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_end_session_request(Msg, TrUserData) -> encode_msg_end_session_request(Msg, <<>>, TrUserData).


encode_msg_end_session_request(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{game_id := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{winner := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= 'SIDE_UNSPECIFIED'; TrF2 =:= 0 -> B1;
                        true -> 'e_enum_alekhine.session.v1.Side'(TrF2, <<B1/binary, 16>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    case M of
        #{reason := F3} ->
            begin
                TrF3 = id(F3, TrUserData),
                case is_empty_string(TrF3) of
                    true -> B2;
                    false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
                end
            end;
        _ -> B2
    end.

encode_msg_snapshot(Msg, TrUserData) -> encode_msg_snapshot(Msg, <<>>, TrUserData).


encode_msg_snapshot(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{game_id := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{status := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= 'SESSION_STATUS_UNSPECIFIED'; TrF2 =:= 0 -> B1;
                        true -> 'e_enum_alekhine.session.v1.SessionStatus'(TrF2, <<B1/binary, 16>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{turn := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     if TrF3 =:= 'SIDE_UNSPECIFIED'; TrF3 =:= 0 -> B2;
                        true -> 'e_enum_alekhine.session.v1.Side'(TrF3, <<B2/binary, 24>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    B4 = case M of
             #{white_ms := F4} ->
                 begin
                     TrF4 = id(F4, TrUserData),
                     if TrF4 =:= 0 -> B3;
                        true -> e_type_int64(TrF4, <<B3/binary, 32>>, TrUserData)
                     end
                 end;
             _ -> B3
         end,
    B5 = case M of
             #{black_ms := F5} ->
                 begin
                     TrF5 = id(F5, TrUserData),
                     if TrF5 =:= 0 -> B4;
                        true -> e_type_int64(TrF5, <<B4/binary, 40>>, TrUserData)
                     end
                 end;
             _ -> B4
         end,
    B6 = case M of
             #{winner := F6} ->
                 begin
                     TrF6 = id(F6, TrUserData),
                     if TrF6 =:= 'SIDE_UNSPECIFIED'; TrF6 =:= 0 -> B5;
                        true -> 'e_enum_alekhine.session.v1.Side'(TrF6, <<B5/binary, 48>>, TrUserData)
                     end
                 end;
             _ -> B5
         end,
    B7 = case M of
             #{reason := F7} ->
                 begin
                     TrF7 = id(F7, TrUserData),
                     case is_empty_string(TrF7) of
                         true -> B6;
                         false -> e_type_string(TrF7, <<B6/binary, 58>>, TrUserData)
                     end
                 end;
             _ -> B6
         end,
    B8 = case M of
             #{spectators := F8} ->
                 TrF8 = id(F8, TrUserData),
                 if TrF8 == [] -> B7;
                    true -> e_field_snapshot_spectators(TrF8, B7, TrUserData)
                 end;
             _ -> B7
         end,
    case M of
        #{error := F9} ->
            begin
                TrF9 = id(F9, TrUserData),
                case is_empty_string(TrF9) of
                    true -> B8;
                    false -> e_type_string(TrF9, <<B8/binary, 74>>, TrUserData)
                end
            end;
        _ -> B8
    end.

e_field_snapshot_spectators([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 66>>,
    Bin3 = e_type_string(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_snapshot_spectators(Rest, Bin3, TrUserData);
e_field_snapshot_spectators([], Bin, _TrUserData) -> Bin.

'e_enum_alekhine.session.v1.Side'('SIDE_UNSPECIFIED', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_alekhine.session.v1.Side'('SIDE_WHITE', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_alekhine.session.v1.Side'('SIDE_BLACK', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_alekhine.session.v1.Side'(V, Bin, _TrUserData) -> e_varint(V, Bin).

'e_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_UNSPECIFIED', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_IN_PROGRESS', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_FINISHED', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_alekhine.session.v1.SessionStatus'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(create_session_request, Bin, TrUserData) -> id(decode_msg_create_session_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(player_ref, Bin, TrUserData) -> id(decode_msg_player_ref(Bin, TrUserData), TrUserData);
decode_msg_2_doit(game_ref, Bin, TrUserData) -> id(decode_msg_game_ref(Bin, TrUserData), TrUserData);
decode_msg_2_doit(end_session_request, Bin, TrUserData) -> id(decode_msg_end_session_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(snapshot, Bin, TrUserData) -> id(decode_msg_snapshot(Bin, TrUserData), TrUserData).



decode_msg_create_session_request(Bin, TrUserData) -> dfp_read_field_def_create_session_request(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(0, TrUserData), id(0, TrUserData), TrUserData).

dfp_read_field_def_create_session_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_game_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_white_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_black_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_initial_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_increment_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_create_session_request_grace_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_create_session_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _) -> #{game_id => F@_1, white_id => F@_2, black_id => F@_3, initial_ms => F@_4, increment_ms => F@_5, grace_ms => F@_6};
dfp_read_field_def_create_session_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dg_read_field_def_create_session_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

dg_read_field_def_create_session_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_create_session_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dg_read_field_def_create_session_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_create_session_request_game_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        18 -> d_field_create_session_request_white_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        26 -> d_field_create_session_request_black_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        32 -> d_field_create_session_request_initial_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        40 -> d_field_create_session_request_increment_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        48 -> d_field_create_session_request_grace_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_create_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                1 -> skip_64_create_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                2 -> skip_length_delimited_create_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                3 -> skip_group_create_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                5 -> skip_32_create_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData)
            end
    end;
dg_read_field_def_create_session_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _) -> #{game_id => F@_1, white_id => F@_2, black_id => F@_3, initial_ms => F@_4, increment_ms => F@_5, grace_ms => F@_6}.

d_field_create_session_request_game_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_game_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_game_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

d_field_create_session_request_white_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_white_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_white_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, TrUserData).

d_field_create_session_request_black_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_black_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_black_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, TrUserData).

d_field_create_session_request_initial_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_initial_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_initial_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, TrUserData).

d_field_create_session_request_increment_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_increment_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_increment_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, TrUserData).

d_field_create_session_request_grace_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_create_session_request_grace_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_create_session_request_grace_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_create_session_request(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, TrUserData).

skip_varint_create_session_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> skip_varint_create_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
skip_varint_create_session_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_create_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_length_delimited_create_session_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    skip_length_delimited_create_session_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
skip_length_delimited_create_session_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_create_session_request(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_group_create_session_request(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_create_session_request(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_32_create_session_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_create_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_64_create_session_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_create_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

decode_msg_player_ref(Bin, TrUserData) -> dfp_read_field_def_player_ref(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_player_ref(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_player_ref_game_id(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_player_ref(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_player_ref_player_id(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_player_ref(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{game_id => F@_1, player_id => F@_2};
dfp_read_field_def_player_ref(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_player_ref(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_player_ref(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_player_ref(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_player_ref(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_player_ref_game_id(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_player_ref_player_id(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_player_ref(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_player_ref(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_player_ref(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_player_ref(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_player_ref(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_player_ref(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{game_id => F@_1, player_id => F@_2}.

d_field_player_ref_game_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_player_ref_game_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_player_ref_game_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_player_ref(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_player_ref_player_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_player_ref_player_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_player_ref_player_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_player_ref(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_player_ref(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_player_ref(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_player_ref(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_player_ref(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_player_ref(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_player_ref(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_player_ref(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_player_ref(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_player_ref(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_player_ref(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_player_ref(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_player_ref(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_player_ref(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_player_ref(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_game_ref(Bin, TrUserData) -> dfp_read_field_def_game_ref(Bin, 0, 0, 0, id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_game_ref(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_game_ref_game_id(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_game_ref(<<>>, 0, 0, _, F@_1, _) -> #{game_id => F@_1};
dfp_read_field_def_game_ref(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_game_ref(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_game_ref(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_game_ref(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_game_ref(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_game_ref_game_id(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_game_ref(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_game_ref(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_game_ref(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_game_ref(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_game_ref(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_game_ref(<<>>, 0, 0, _, F@_1, _) -> #{game_id => F@_1}.

d_field_game_ref_game_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_game_ref_game_id(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_game_ref_game_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_game_ref(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_game_ref(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_game_ref(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_game_ref(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_game_ref(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_game_ref(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_game_ref(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_game_ref(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_game_ref(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_game_ref(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_game_ref(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_game_ref(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_game_ref(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_game_ref(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_game_ref(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_end_session_request(Bin, TrUserData) -> dfp_read_field_def_end_session_request(Bin, 0, 0, 0, id(<<>>, TrUserData), id('SIDE_UNSPECIFIED', TrUserData), id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_end_session_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_end_session_request_game_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_end_session_request(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_end_session_request_winner(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_end_session_request(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_end_session_request_reason(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_end_session_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{game_id => F@_1, winner => F@_2, reason => F@_3};
dfp_read_field_def_end_session_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_end_session_request(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_end_session_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_end_session_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_end_session_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_end_session_request_game_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        16 -> d_field_end_session_request_winner(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        26 -> d_field_end_session_request_reason(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_end_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> skip_64_end_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> skip_length_delimited_end_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> skip_group_end_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> skip_32_end_session_request(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
dg_read_field_def_end_session_request(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{game_id => F@_1, winner => F@_2, reason => F@_3}.

d_field_end_session_request_game_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_end_session_request_game_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_end_session_request_game_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_end_session_request(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_end_session_request_winner(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_end_session_request_winner(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_end_session_request_winner(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_alekhine.session.v1.Side'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_end_session_request(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

d_field_end_session_request_reason(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_end_session_request_reason(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_end_session_request_reason(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_end_session_request(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_end_session_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_end_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_end_session_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_end_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_end_session_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_end_session_request(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_end_session_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_end_session_request(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_end_session_request(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_end_session_request(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_end_session_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_end_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_end_session_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_end_session_request(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_snapshot(Bin, TrUserData) ->
    dfp_read_field_def_snapshot(Bin,
                                0,
                                0,
                                0,
                                id(<<>>, TrUserData),
                                id('SESSION_STATUS_UNSPECIFIED', TrUserData),
                                id('SIDE_UNSPECIFIED', TrUserData),
                                id(0, TrUserData),
                                id(0, TrUserData),
                                id('SIDE_UNSPECIFIED', TrUserData),
                                id(<<>>, TrUserData),
                                id([], TrUserData),
                                id(<<>>, TrUserData),
                                TrUserData).

dfp_read_field_def_snapshot(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_game_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_status(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_turn(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_white_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_black_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_winner(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<58, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_reason(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<66, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_spectators(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<74, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> d_field_snapshot_error(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dfp_read_field_def_snapshot(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, R1, F@_9, TrUserData) ->
    #{game_id => F@_1, status => F@_2, turn => F@_3, white_ms => F@_4, black_ms => F@_5, winner => F@_6, reason => F@_7, spectators => lists_reverse(R1, TrUserData), error => F@_9};
dfp_read_field_def_snapshot(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> dg_read_field_def_snapshot(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

dg_read_field_def_snapshot(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_snapshot(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
dg_read_field_def_snapshot(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_snapshot_game_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        16 -> d_field_snapshot_status(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        24 -> d_field_snapshot_turn(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        32 -> d_field_snapshot_white_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        40 -> d_field_snapshot_black_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        48 -> d_field_snapshot_winner(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        58 -> d_field_snapshot_reason(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        66 -> d_field_snapshot_spectators(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        74 -> d_field_snapshot_error(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_snapshot(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
                1 -> skip_64_snapshot(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
                2 -> skip_length_delimited_snapshot(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
                3 -> skip_group_snapshot(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
                5 -> skip_32_snapshot(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData)
            end
    end;
dg_read_field_def_snapshot(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, R1, F@_9, TrUserData) ->
    #{game_id => F@_1, status => F@_2, turn => F@_3, white_ms => F@_4, black_ms => F@_5, winner => F@_6, reason => F@_7, spectators => lists_reverse(R1, TrUserData), error => F@_9}.

d_field_snapshot_game_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_game_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_game_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_snapshot(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_status(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_status(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_status(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_alekhine.session.v1.SessionStatus'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_turn(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_turn(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_turn(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_alekhine.session.v1.Side'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_white_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_white_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_white_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_black_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_black_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_black_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_winner(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_winner(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_winner(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_alekhine.session.v1.Side'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, F@_8, F@_9, TrUserData).

d_field_snapshot_reason(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_reason(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_reason(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, F@_8, F@_9, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, F@_8, F@_9, TrUserData).

d_field_snapshot_spectators(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_spectators(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_spectators(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, Prev, F@_9, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, cons(NewFValue, Prev, TrUserData), F@_9, TrUserData).

d_field_snapshot_error(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    d_field_snapshot_error(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
d_field_snapshot_error(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_snapshot(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, NewFValue, TrUserData).

skip_varint_snapshot(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> skip_varint_snapshot(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
skip_varint_snapshot(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> dfp_read_field_def_snapshot(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

skip_length_delimited_snapshot(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) when N < 57 ->
    skip_length_delimited_snapshot(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData);
skip_length_delimited_snapshot(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_snapshot(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

skip_group_snapshot(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_snapshot(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

skip_32_snapshot(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> dfp_read_field_def_snapshot(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

skip_64_snapshot(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData) -> dfp_read_field_def_snapshot(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, TrUserData).

'd_enum_alekhine.session.v1.Side'(0) -> 'SIDE_UNSPECIFIED';
'd_enum_alekhine.session.v1.Side'(1) -> 'SIDE_WHITE';
'd_enum_alekhine.session.v1.Side'(2) -> 'SIDE_BLACK';
'd_enum_alekhine.session.v1.Side'(V) -> V.

'd_enum_alekhine.session.v1.SessionStatus'(0) -> 'SESSION_STATUS_UNSPECIFIED';
'd_enum_alekhine.session.v1.SessionStatus'(1) -> 'SESSION_STATUS_IN_PROGRESS';
'd_enum_alekhine.session.v1.SessionStatus'(2) -> 'SESSION_STATUS_FINISHED';
'd_enum_alekhine.session.v1.SessionStatus'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_session_request -> merge_msg_create_session_request(Prev, New, TrUserData);
        player_ref -> merge_msg_player_ref(Prev, New, TrUserData);
        game_ref -> merge_msg_game_ref(Prev, New, TrUserData);
        end_session_request -> merge_msg_end_session_request(Prev, New, TrUserData);
        snapshot -> merge_msg_snapshot(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_create_session_request/3}).
merge_msg_create_session_request(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{game_id := NFgame_id}} -> S1#{game_id => NFgame_id};
             {#{game_id := PFgame_id}, _} -> S1#{game_id => PFgame_id};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{white_id := NFwhite_id}} -> S2#{white_id => NFwhite_id};
             {#{white_id := PFwhite_id}, _} -> S2#{white_id => PFwhite_id};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{black_id := NFblack_id}} -> S3#{black_id => NFblack_id};
             {#{black_id := PFblack_id}, _} -> S3#{black_id => PFblack_id};
             _ -> S3
         end,
    S5 = case {PMsg, NMsg} of
             {_, #{initial_ms := NFinitial_ms}} -> S4#{initial_ms => NFinitial_ms};
             {#{initial_ms := PFinitial_ms}, _} -> S4#{initial_ms => PFinitial_ms};
             _ -> S4
         end,
    S6 = case {PMsg, NMsg} of
             {_, #{increment_ms := NFincrement_ms}} -> S5#{increment_ms => NFincrement_ms};
             {#{increment_ms := PFincrement_ms}, _} -> S5#{increment_ms => PFincrement_ms};
             _ -> S5
         end,
    case {PMsg, NMsg} of
        {_, #{grace_ms := NFgrace_ms}} -> S6#{grace_ms => NFgrace_ms};
        {#{grace_ms := PFgrace_ms}, _} -> S6#{grace_ms => PFgrace_ms};
        _ -> S6
    end.

-compile({nowarn_unused_function,merge_msg_player_ref/3}).
merge_msg_player_ref(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{game_id := NFgame_id}} -> S1#{game_id => NFgame_id};
             {#{game_id := PFgame_id}, _} -> S1#{game_id => PFgame_id};
             _ -> S1
         end,
    case {PMsg, NMsg} of
        {_, #{player_id := NFplayer_id}} -> S2#{player_id => NFplayer_id};
        {#{player_id := PFplayer_id}, _} -> S2#{player_id => PFplayer_id};
        _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_game_ref/3}).
merge_msg_game_ref(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{game_id := NFgame_id}} -> S1#{game_id => NFgame_id};
        {#{game_id := PFgame_id}, _} -> S1#{game_id => PFgame_id};
        _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_end_session_request/3}).
merge_msg_end_session_request(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{game_id := NFgame_id}} -> S1#{game_id => NFgame_id};
             {#{game_id := PFgame_id}, _} -> S1#{game_id => PFgame_id};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{winner := NFwinner}} -> S2#{winner => NFwinner};
             {#{winner := PFwinner}, _} -> S2#{winner => PFwinner};
             _ -> S2
         end,
    case {PMsg, NMsg} of
        {_, #{reason := NFreason}} -> S3#{reason => NFreason};
        {#{reason := PFreason}, _} -> S3#{reason => PFreason};
        _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_snapshot/3}).
merge_msg_snapshot(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{game_id := NFgame_id}} -> S1#{game_id => NFgame_id};
             {#{game_id := PFgame_id}, _} -> S1#{game_id => PFgame_id};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{status := NFstatus}} -> S2#{status => NFstatus};
             {#{status := PFstatus}, _} -> S2#{status => PFstatus};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{turn := NFturn}} -> S3#{turn => NFturn};
             {#{turn := PFturn}, _} -> S3#{turn => PFturn};
             _ -> S3
         end,
    S5 = case {PMsg, NMsg} of
             {_, #{white_ms := NFwhite_ms}} -> S4#{white_ms => NFwhite_ms};
             {#{white_ms := PFwhite_ms}, _} -> S4#{white_ms => PFwhite_ms};
             _ -> S4
         end,
    S6 = case {PMsg, NMsg} of
             {_, #{black_ms := NFblack_ms}} -> S5#{black_ms => NFblack_ms};
             {#{black_ms := PFblack_ms}, _} -> S5#{black_ms => PFblack_ms};
             _ -> S5
         end,
    S7 = case {PMsg, NMsg} of
             {_, #{winner := NFwinner}} -> S6#{winner => NFwinner};
             {#{winner := PFwinner}, _} -> S6#{winner => PFwinner};
             _ -> S6
         end,
    S8 = case {PMsg, NMsg} of
             {_, #{reason := NFreason}} -> S7#{reason => NFreason};
             {#{reason := PFreason}, _} -> S7#{reason => PFreason};
             _ -> S7
         end,
    S9 = case {PMsg, NMsg} of
             {#{spectators := PFspectators}, #{spectators := NFspectators}} -> S8#{spectators => 'erlang_++'(PFspectators, NFspectators, TrUserData)};
             {_, #{spectators := NFspectators}} -> S8#{spectators => NFspectators};
             {#{spectators := PFspectators}, _} -> S8#{spectators => PFspectators};
             {_, _} -> S8
         end,
    case {PMsg, NMsg} of
        {_, #{error := NFerror}} -> S9#{error => NFerror};
        {#{error := PFerror}, _} -> S9#{error => PFerror};
        _ -> S9
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        create_session_request -> v_msg_create_session_request(Msg, [MsgName], TrUserData);
        player_ref -> v_msg_player_ref(Msg, [MsgName], TrUserData);
        game_ref -> v_msg_game_ref(Msg, [MsgName], TrUserData);
        end_session_request -> v_msg_end_session_request(Msg, [MsgName], TrUserData);
        snapshot -> v_msg_snapshot(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_create_session_request/3}).
-dialyzer({nowarn_function,v_msg_create_session_request/3}).
v_msg_create_session_request(#{} = M, Path, TrUserData) ->
    case M of
        #{game_id := F1} -> v_type_string(F1, [game_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{white_id := F2} -> v_type_string(F2, [white_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{black_id := F3} -> v_type_string(F3, [black_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{initial_ms := F4} -> v_type_int64(F4, [initial_ms | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{increment_ms := F5} -> v_type_int64(F5, [increment_ms | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{grace_ms := F6} -> v_type_int64(F6, [grace_ms | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (game_id) -> ok;
                      (white_id) -> ok;
                      (black_id) -> ok;
                      (initial_ms) -> ok;
                      (increment_ms) -> ok;
                      (grace_ms) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_create_session_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), create_session_request}, M, Path);
v_msg_create_session_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, create_session_request}, X, Path).

-compile({nowarn_unused_function,v_msg_player_ref/3}).
-dialyzer({nowarn_function,v_msg_player_ref/3}).
v_msg_player_ref(#{} = M, Path, TrUserData) ->
    case M of
        #{game_id := F1} -> v_type_string(F1, [game_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{player_id := F2} -> v_type_string(F2, [player_id | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (game_id) -> ok;
                      (player_id) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_player_ref(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), player_ref}, M, Path);
v_msg_player_ref(X, Path, _TrUserData) -> mk_type_error({expected_msg, player_ref}, X, Path).

-compile({nowarn_unused_function,v_msg_game_ref/3}).
-dialyzer({nowarn_function,v_msg_game_ref/3}).
v_msg_game_ref(#{} = M, Path, TrUserData) ->
    case M of
        #{game_id := F1} -> v_type_string(F1, [game_id | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (game_id) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_game_ref(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), game_ref}, M, Path);
v_msg_game_ref(X, Path, _TrUserData) -> mk_type_error({expected_msg, game_ref}, X, Path).

-compile({nowarn_unused_function,v_msg_end_session_request/3}).
-dialyzer({nowarn_function,v_msg_end_session_request/3}).
v_msg_end_session_request(#{} = M, Path, TrUserData) ->
    case M of
        #{game_id := F1} -> v_type_string(F1, [game_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{winner := F2} -> 'v_enum_alekhine.session.v1.Side'(F2, [winner | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{reason := F3} -> v_type_string(F3, [reason | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (game_id) -> ok;
                      (winner) -> ok;
                      (reason) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_end_session_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), end_session_request}, M, Path);
v_msg_end_session_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, end_session_request}, X, Path).

-compile({nowarn_unused_function,v_msg_snapshot/3}).
-dialyzer({nowarn_function,v_msg_snapshot/3}).
v_msg_snapshot(#{} = M, Path, TrUserData) ->
    case M of
        #{game_id := F1} -> v_type_string(F1, [game_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{status := F2} -> 'v_enum_alekhine.session.v1.SessionStatus'(F2, [status | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{turn := F3} -> 'v_enum_alekhine.session.v1.Side'(F3, [turn | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{white_ms := F4} -> v_type_int64(F4, [white_ms | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{black_ms := F5} -> v_type_int64(F5, [black_ms | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{winner := F6} -> 'v_enum_alekhine.session.v1.Side'(F6, [winner | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{reason := F7} -> v_type_string(F7, [reason | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{spectators := F8} ->
            if is_list(F8) ->
                   _ = [v_type_string(Elem, [spectators | Path], TrUserData) || Elem <- F8],
                   ok;
               true -> mk_type_error({invalid_list_of, string}, F8, [spectators | Path])
            end;
        _ -> ok
    end,
    case M of
        #{error := F9} -> v_type_string(F9, [error | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (game_id) -> ok;
                      (status) -> ok;
                      (turn) -> ok;
                      (white_ms) -> ok;
                      (black_ms) -> ok;
                      (winner) -> ok;
                      (reason) -> ok;
                      (spectators) -> ok;
                      (error) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_snapshot(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), snapshot}, M, Path);
v_msg_snapshot(X, Path, _TrUserData) -> mk_type_error({expected_msg, snapshot}, X, Path).

-compile({nowarn_unused_function,'v_enum_alekhine.session.v1.Side'/3}).
-dialyzer({nowarn_function,'v_enum_alekhine.session.v1.Side'/3}).
'v_enum_alekhine.session.v1.Side'('SIDE_UNSPECIFIED', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.Side'('SIDE_WHITE', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.Side'('SIDE_BLACK', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.Side'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_alekhine.session.v1.Side'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'alekhine.session.v1.Side'}, X, Path).

-compile({nowarn_unused_function,'v_enum_alekhine.session.v1.SessionStatus'/3}).
-dialyzer({nowarn_function,'v_enum_alekhine.session.v1.SessionStatus'/3}).
'v_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_UNSPECIFIED', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_IN_PROGRESS', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.SessionStatus'('SESSION_STATUS_FINISHED', _Path, _TrUserData) -> ok;
'v_enum_alekhine.session.v1.SessionStatus'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_alekhine.session.v1.SessionStatus'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'alekhine.session.v1.SessionStatus'}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when is_integer(N), -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'alekhine.session.v1.Side'}, [{'SIDE_UNSPECIFIED', 0}, {'SIDE_WHITE', 1}, {'SIDE_BLACK', 2}]},
     {{enum, 'alekhine.session.v1.SessionStatus'}, [{'SESSION_STATUS_UNSPECIFIED', 0}, {'SESSION_STATUS_IN_PROGRESS', 1}, {'SESSION_STATUS_FINISHED', 2}]},
     {{msg, create_session_request},
      [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
       #{name => white_id, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
       #{name => black_id, fnum => 3, rnum => 4, type => string, occurrence => optional, opts => []},
       #{name => initial_ms, fnum => 4, rnum => 5, type => int64, occurrence => optional, opts => []},
       #{name => increment_ms, fnum => 5, rnum => 6, type => int64, occurrence => optional, opts => []},
       #{name => grace_ms, fnum => 6, rnum => 7, type => int64, occurrence => optional, opts => []}]},
     {{msg, player_ref}, [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => player_id, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}]},
     {{msg, game_ref}, [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}]},
     {{msg, end_session_request},
      [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
       #{name => winner, fnum => 2, rnum => 3, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
       #{name => reason, fnum => 3, rnum => 4, type => string, occurrence => optional, opts => []}]},
     {{msg, snapshot},
      [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
       #{name => status, fnum => 2, rnum => 3, type => {enum, 'alekhine.session.v1.SessionStatus'}, occurrence => optional, opts => []},
       #{name => turn, fnum => 3, rnum => 4, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
       #{name => white_ms, fnum => 4, rnum => 5, type => int64, occurrence => optional, opts => []},
       #{name => black_ms, fnum => 5, rnum => 6, type => int64, occurrence => optional, opts => []},
       #{name => winner, fnum => 6, rnum => 7, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
       #{name => reason, fnum => 7, rnum => 8, type => string, occurrence => optional, opts => []},
       #{name => spectators, fnum => 8, rnum => 9, type => string, occurrence => repeated, opts => []},
       #{name => error, fnum => 9, rnum => 10, type => string, occurrence => optional, opts => []}]}].


get_msg_names() -> [create_session_request, player_ref, game_ref, end_session_request, snapshot].


get_group_names() -> [].


get_msg_or_group_names() -> [create_session_request, player_ref, game_ref, end_session_request, snapshot].


get_enum_names() -> ['alekhine.session.v1.Side', 'alekhine.session.v1.SessionStatus'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
        Es when is_list(Es) -> Es;
        error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(create_session_request) ->
    [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
     #{name => white_id, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
     #{name => black_id, fnum => 3, rnum => 4, type => string, occurrence => optional, opts => []},
     #{name => initial_ms, fnum => 4, rnum => 5, type => int64, occurrence => optional, opts => []},
     #{name => increment_ms, fnum => 5, rnum => 6, type => int64, occurrence => optional, opts => []},
     #{name => grace_ms, fnum => 6, rnum => 7, type => int64, occurrence => optional, opts => []}];
find_msg_def(player_ref) -> [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}, #{name => player_id, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []}];
find_msg_def(game_ref) -> [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}];
find_msg_def(end_session_request) ->
    [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
     #{name => winner, fnum => 2, rnum => 3, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
     #{name => reason, fnum => 3, rnum => 4, type => string, occurrence => optional, opts => []}];
find_msg_def(snapshot) ->
    [#{name => game_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
     #{name => status, fnum => 2, rnum => 3, type => {enum, 'alekhine.session.v1.SessionStatus'}, occurrence => optional, opts => []},
     #{name => turn, fnum => 3, rnum => 4, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
     #{name => white_ms, fnum => 4, rnum => 5, type => int64, occurrence => optional, opts => []},
     #{name => black_ms, fnum => 5, rnum => 6, type => int64, occurrence => optional, opts => []},
     #{name => winner, fnum => 6, rnum => 7, type => {enum, 'alekhine.session.v1.Side'}, occurrence => optional, opts => []},
     #{name => reason, fnum => 7, rnum => 8, type => string, occurrence => optional, opts => []},
     #{name => spectators, fnum => 8, rnum => 9, type => string, occurrence => repeated, opts => []},
     #{name => error, fnum => 9, rnum => 10, type => string, occurrence => optional, opts => []}];
find_msg_def(_) -> error.


find_enum_def('alekhine.session.v1.Side') -> [{'SIDE_UNSPECIFIED', 0}, {'SIDE_WHITE', 1}, {'SIDE_BLACK', 2}];
find_enum_def('alekhine.session.v1.SessionStatus') -> [{'SESSION_STATUS_UNSPECIFIED', 0}, {'SESSION_STATUS_IN_PROGRESS', 1}, {'SESSION_STATUS_FINISHED', 2}];
find_enum_def(_) -> error.


enum_symbol_by_value('alekhine.session.v1.Side', Value) -> 'enum_symbol_by_value_alekhine.session.v1.Side'(Value);
enum_symbol_by_value('alekhine.session.v1.SessionStatus', Value) -> 'enum_symbol_by_value_alekhine.session.v1.SessionStatus'(Value).


enum_value_by_symbol('alekhine.session.v1.Side', Sym) -> 'enum_value_by_symbol_alekhine.session.v1.Side'(Sym);
enum_value_by_symbol('alekhine.session.v1.SessionStatus', Sym) -> 'enum_value_by_symbol_alekhine.session.v1.SessionStatus'(Sym).


'enum_symbol_by_value_alekhine.session.v1.Side'(0) -> 'SIDE_UNSPECIFIED';
'enum_symbol_by_value_alekhine.session.v1.Side'(1) -> 'SIDE_WHITE';
'enum_symbol_by_value_alekhine.session.v1.Side'(2) -> 'SIDE_BLACK'.


'enum_value_by_symbol_alekhine.session.v1.Side'('SIDE_UNSPECIFIED') -> 0;
'enum_value_by_symbol_alekhine.session.v1.Side'('SIDE_WHITE') -> 1;
'enum_value_by_symbol_alekhine.session.v1.Side'('SIDE_BLACK') -> 2.

'enum_symbol_by_value_alekhine.session.v1.SessionStatus'(0) -> 'SESSION_STATUS_UNSPECIFIED';
'enum_symbol_by_value_alekhine.session.v1.SessionStatus'(1) -> 'SESSION_STATUS_IN_PROGRESS';
'enum_symbol_by_value_alekhine.session.v1.SessionStatus'(2) -> 'SESSION_STATUS_FINISHED'.


'enum_value_by_symbol_alekhine.session.v1.SessionStatus'('SESSION_STATUS_UNSPECIFIED') -> 0;
'enum_value_by_symbol_alekhine.session.v1.SessionStatus'('SESSION_STATUS_IN_PROGRESS') -> 1;
'enum_value_by_symbol_alekhine.session.v1.SessionStatus'('SESSION_STATUS_FINISHED') -> 2.


get_service_names() -> ['alekhine.session.v1.SessionService'].


get_service_def('alekhine.session.v1.SessionService') ->
    {{service, 'alekhine.session.v1.SessionService'},
     [#{name => 'CreateSession', input => create_session_request, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'Join', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'MoveMade', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'Disconnect', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'Reconnect', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'Resign', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'EndSession', input => end_session_request, output => snapshot, input_stream => false, output_stream => false, opts => []},
      #{name => 'GetSnapshot', input => game_ref, output => snapshot, input_stream => false, output_stream => false, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('alekhine.session.v1.SessionService') -> ['CreateSession', 'Join', 'MoveMade', 'Disconnect', 'Reconnect', 'Resign', 'EndSession', 'GetSnapshot'];
get_rpc_names(_) -> error.


find_rpc_def('alekhine.session.v1.SessionService', RpcName) -> 'find_rpc_def_alekhine.session.v1.SessionService'(RpcName);
find_rpc_def(_, _) -> error.


'find_rpc_def_alekhine.session.v1.SessionService'('CreateSession') -> #{name => 'CreateSession', input => create_session_request, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('Join') -> #{name => 'Join', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('MoveMade') -> #{name => 'MoveMade', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('Disconnect') -> #{name => 'Disconnect', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('Reconnect') -> #{name => 'Reconnect', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('Resign') -> #{name => 'Resign', input => player_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('EndSession') -> #{name => 'EndSession', input => end_session_request, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'('GetSnapshot') -> #{name => 'GetSnapshot', input => game_ref, output => snapshot, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_alekhine.session.v1.SessionService'(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_map(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"alekhine.session.v1.SessionService">>) -> 'alekhine.session.v1.SessionService';
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin('alekhine.session.v1.SessionService') -> <<"alekhine.session.v1.SessionService">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"CreateSession">>) -> {'alekhine.session.v1.SessionService', 'CreateSession'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"Join">>) -> {'alekhine.session.v1.SessionService', 'Join'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"MoveMade">>) -> {'alekhine.session.v1.SessionService', 'MoveMade'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"Disconnect">>) -> {'alekhine.session.v1.SessionService', 'Disconnect'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"Reconnect">>) -> {'alekhine.session.v1.SessionService', 'Reconnect'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"Resign">>) -> {'alekhine.session.v1.SessionService', 'Resign'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"EndSession">>) -> {'alekhine.session.v1.SessionService', 'EndSession'};
fqbins_to_service_and_rpc_name(<<"alekhine.session.v1.SessionService">>, <<"GetSnapshot">>) -> {'alekhine.session.v1.SessionService', 'GetSnapshot'};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'CreateSession') -> {<<"alekhine.session.v1.SessionService">>, <<"CreateSession">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'Join') -> {<<"alekhine.session.v1.SessionService">>, <<"Join">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'MoveMade') -> {<<"alekhine.session.v1.SessionService">>, <<"MoveMade">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'Disconnect') -> {<<"alekhine.session.v1.SessionService">>, <<"Disconnect">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'Reconnect') -> {<<"alekhine.session.v1.SessionService">>, <<"Reconnect">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'Resign') -> {<<"alekhine.session.v1.SessionService">>, <<"Resign">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'EndSession') -> {<<"alekhine.session.v1.SessionService">>, <<"EndSession">>};
service_and_rpc_name_to_fqbins('alekhine.session.v1.SessionService', 'GetSnapshot') -> {<<"alekhine.session.v1.SessionService">>, <<"GetSnapshot">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"alekhine.session.v1.CreateSessionRequest">>) -> create_session_request;
fqbin_to_msg_name(<<"alekhine.session.v1.PlayerRef">>) -> player_ref;
fqbin_to_msg_name(<<"alekhine.session.v1.GameRef">>) -> game_ref;
fqbin_to_msg_name(<<"alekhine.session.v1.EndSessionRequest">>) -> end_session_request;
fqbin_to_msg_name(<<"alekhine.session.v1.Snapshot">>) -> snapshot;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(create_session_request) -> <<"alekhine.session.v1.CreateSessionRequest">>;
msg_name_to_fqbin(player_ref) -> <<"alekhine.session.v1.PlayerRef">>;
msg_name_to_fqbin(game_ref) -> <<"alekhine.session.v1.GameRef">>;
msg_name_to_fqbin(end_session_request) -> <<"alekhine.session.v1.EndSessionRequest">>;
msg_name_to_fqbin(snapshot) -> <<"alekhine.session.v1.Snapshot">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"alekhine.session.v1.Side">>) -> 'alekhine.session.v1.Side';
fqbin_to_enum_name(<<"alekhine.session.v1.SessionStatus">>) -> 'alekhine.session.v1.SessionStatus';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('alekhine.session.v1.Side') -> <<"alekhine.session.v1.Side">>;
enum_name_to_fqbin('alekhine.session.v1.SessionStatus') -> <<"alekhine.session.v1.SessionStatus">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'alekhine.session.v1'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "session.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["session.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["session"].


get_msg_containment("session") -> [create_session_request, end_session_request, game_ref, player_ref, snapshot];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("session") -> 'alekhine.session.v1';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("session") -> ['alekhine.session.v1.SessionService'];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("session") ->
    [{'alekhine.session.v1.SessionService', 'CreateSession'},
     {'alekhine.session.v1.SessionService', 'Join'},
     {'alekhine.session.v1.SessionService', 'MoveMade'},
     {'alekhine.session.v1.SessionService', 'Disconnect'},
     {'alekhine.session.v1.SessionService', 'Reconnect'},
     {'alekhine.session.v1.SessionService', 'Resign'},
     {'alekhine.session.v1.SessionService', 'EndSession'},
     {'alekhine.session.v1.SessionService', 'GetSnapshot'}];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("session") -> ['alekhine.session.v1.SessionStatus', 'alekhine.session.v1.Side'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"alekhine.session.v1.Snapshot">>) -> "session";
get_proto_by_msg_name_as_fqbin(<<"alekhine.session.v1.EndSessionRequest">>) -> "session";
get_proto_by_msg_name_as_fqbin(<<"alekhine.session.v1.CreateSessionRequest">>) -> "session";
get_proto_by_msg_name_as_fqbin(<<"alekhine.session.v1.PlayerRef">>) -> "session";
get_proto_by_msg_name_as_fqbin(<<"alekhine.session.v1.GameRef">>) -> "session";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"alekhine.session.v1.SessionService">>) -> "session";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"alekhine.session.v1.SessionStatus">>) -> "session";
get_proto_by_enum_name_as_fqbin(<<"alekhine.session.v1.Side">>) -> "session";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"alekhine.session.v1">>) -> ["session"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.21.7".

gpb_version_as_list() ->
    [4,21,7].

gpb_version_source() ->
    "file".
