package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	gamev1 "github.com/IshaanNene/AlekhinesCounter-Gambit/proto/gen/go/game/v1"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/generated"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/model"
)

// Clock is the resolver for the clock field.
//
// Live clocks live in the session-manager, which only tracks human-vs-human
// games. A missing session is not an error: it resolves to null.
func (r *gameResolver) Clock(ctx context.Context, obj *model.Game) (*model.Clock, error) {
	if obj.VsEngine || !r.Upstream.SessionEnabled() {
		return nil, nil
	}
	snap, err := r.Upstream.Snapshot(ctx, obj.ID)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		r.Log.Warn("session snapshot failed", "game_id", obj.ID, "error", err)
		return nil, nil
	}
	return toModelClock(snap), nil
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.CreateGame(ctx, &gamev1.CreateGameRequest{
		WhiteId:     deref(input.WhiteID),
		BlackId:     deref(input.BlackID),
		EngineDepth: uint32(derefInt(input.EngineDepth)),
		InitialMs:   int64(derefInt(input.InitialMs)),
		IncrementMs: int64(derefInt(input.IncrementMs)),
	})
	if err != nil {
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, input model.MoveInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.SubmitMove(ctx, &gamev1.SubmitMoveRequest{
		GameId:   input.GameID,
		Uci:      input.Uci,
		PlayerId: deref(input.PlayerID),
	})
	if err != nil {
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Resign is the resolver for the resign field.
func (r *mutationResolver) Resign(ctx context.Context, input model.ResignInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.Resign(ctx, &gamev1.ResignRequest{
		GameId:   input.GameID,
		PlayerId: input.PlayerID,
	})
	if err != nil {
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Game is the resolver for the game field. An unknown id resolves to null
// rather than an error, per GraphQL convention for nullable lookups.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	resp, err := r.Upstream.Game.GetGame(ctx, &gamev1.GetGameRequest{GameId: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Game returns generated.GameResolver implementation.
func (r *Resolver) Game() generated.GameResolver { return &gameResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type gameResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// deref returns the pointed-to string, or "" for nil (the proto zero value the
// backends already treat as "unset").
func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func derefInt(i *int) int {
	if i == nil {
		return 0
	}
	return *i
}
