package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	gamev1 "github.com/IshaanNene/AlekhinesCounter-Gambit/proto/gen/go/game/v1"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/generated"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/model"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Clock is the resolver for the clock field.
//
// Live clocks live in the session-manager, which only tracks human-vs-human
// games. A missing session is not an error: it resolves to null.
func (r *gameResolver) Clock(ctx context.Context, obj *model.Game) (*model.Clock, error) {
	if obj.VsEngine || !r.Upstream.SessionEnabled() {
		return nil, nil
	}
	snap, err := r.Upstream.Snapshot(ctx, obj.ID)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		r.Log.Warn("session snapshot failed", "game_id", obj.ID, "error", err)
		return nil, nil
	}
	return toModelClock(snap), nil
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.CreateGame(ctx, &gamev1.CreateGameRequest{
		WhiteId:     deref(input.WhiteID),
		BlackId:     deref(input.BlackID),
		EngineDepth: uint32(derefInt(input.EngineDepth)),
		InitialMs:   int64(derefInt(input.InitialMs)),
		IncrementMs: int64(derefInt(input.IncrementMs)),
	})
	if err != nil {
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, input model.MoveInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.SubmitMove(ctx, &gamev1.SubmitMoveRequest{
		GameId:   input.GameID,
		Uci:      input.Uci,
		PlayerId: deref(input.PlayerID),
	})
	if err != nil {
		return nil, err
	}
	g := toModelGame(resp.GetGame())
	r.publish(ctx, g)
	return g, nil
}

// Resign is the resolver for the resign field.
func (r *mutationResolver) Resign(ctx context.Context, input model.ResignInput) (*model.Game, error) {
	resp, err := r.Upstream.Game.Resign(ctx, &gamev1.ResignRequest{
		GameId:   input.GameID,
		PlayerId: input.PlayerID,
	})
	if err != nil {
		return nil, err
	}
	g := toModelGame(resp.GetGame())
	r.publish(ctx, g)
	return g, nil
}

// Game is the resolver for the game field. An unknown id resolves to null
// rather than an error, per GraphQL convention for nullable lookups.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	resp, err := r.Upstream.Game.GetGame(ctx, &gamev1.GetGameRequest{GameId: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// GameUpdated is the resolver for the gameUpdated field.
//
// Emits the game's current state immediately so a joining client renders a board
// straight away, then forwards every subsequent update published by the move and
// resign mutations. The channel closes when the client disconnects (ctx done).
func (r *subscriptionResolver) GameUpdated(ctx context.Context, gameID string) (<-chan *model.Game, error) {
	updates, err := r.Bus.Subscribe(ctx, gameID)
	if err != nil {
		return nil, err
	}

	// Fetch the current state before relaying, so a late joiner is not blank
	// until the next move. A missing game is a hard error here (unlike the
	// nullable `game` query): subscribing to nothing is a client mistake.
	current, err := r.Upstream.Game.GetGame(ctx, &gamev1.GetGameRequest{GameId: gameID})
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Game, 1)
	out <- toModelGame(current.GetGame())

	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case g, ok := <-updates:
				if !ok {
					return
				}
				select {
				case out <- g:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Game returns generated.GameResolver implementation.
func (r *Resolver) Game() generated.GameResolver { return &gameResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	gameResolver         struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
