package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	authv1 "github.com/IshaanNene/AlekhinesCounter-Gambit/proto/gen/go/auth/v1"
	gamev1 "github.com/IshaanNene/AlekhinesCounter-Gambit/proto/gen/go/game/v1"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/generated"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/graph/model"
	"github.com/IshaanNene/AlekhinesCounter-Gambit/services/gateway/internal/auth"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Clock is the resolver for the clock field.
//
// Live clocks live in the session-manager, which only tracks human-vs-human
// games. A missing session is not an error: it resolves to null.
func (r *gameResolver) Clock(ctx context.Context, obj *model.Game) (*model.Clock, error) {
	if obj.VsEngine || !r.Upstream.SessionEnabled() {
		return nil, nil
	}
	snap, err := r.Upstream.Snapshot(ctx, obj.ID)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		r.Log.Warn("session snapshot failed", "game_id", obj.ID, "error", err)
		return nil, nil
	}
	return toModelClock(snap), nil
}

// LoginAsGuest is the resolver for the loginAsGuest field.
func (r *mutationResolver) LoginAsGuest(ctx context.Context) (*model.Session, error) {
	resp, err := r.Upstream.Auth.CreateGuest(ctx, &authv1.CreateGuestRequest{})
	if err != nil {
		return nil, err
	}
	return r.startSession(ctx, resp.GetUser())
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.Session, error) {
	req := &authv1.RegisterRequest{
		Username: input.Username,
		Password: input.Password,
		Email:    deref(input.Email),
	}
	// Upgrading keeps the caller's existing id, so games and rating earned as a
	// guest survive signing up. Only ever upgrade the *current* guest — taking a
	// user id from the client would let anyone hijack another account.
	if input.UpgradeCurrentGuest != nil && *input.UpgradeCurrentGuest {
		if id, err := auth.FromContext(ctx); err == nil && id.IsGuest {
			req.UpgradeUserId = id.UserID
		}
	}
	resp, err := r.Upstream.Auth.Register(ctx, req)
	if err != nil {
		return nil, err
	}
	return r.startSession(ctx, resp.GetUser())
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.Session, error) {
	resp, err := r.Upstream.Auth.Login(ctx, &authv1.LoginRequest{
		Identifier: input.Identifier,
		Password:   input.Password,
	})
	if err != nil {
		return nil, err
	}
	return r.startSession(ctx, resp.GetUser())
}

// RequestLoginToken is the resolver for the requestLoginToken field.
func (r *mutationResolver) RequestLoginToken(ctx context.Context, email string) (*model.LoginTokenRequest, error) {
	resp, err := r.Upstream.Auth.RequestLoginToken(ctx, &authv1.RequestLoginTokenRequest{Email: email})
	if err != nil {
		return nil, err
	}
	out := &model.LoginTokenRequest{DeliveredInBand: resp.GetDeliveredInBand()}
	if t := resp.GetToken(); t != "" {
		out.Token = &t
	}
	if resp.GetExpiresAt() != nil {
		at := resp.GetExpiresAt().AsTime()
		out.ExpiresAt = &at
	}
	return out, nil
}

// RedeemLoginToken is the resolver for the redeemLoginToken field.
func (r *mutationResolver) RedeemLoginToken(ctx context.Context, token string) (*model.Session, error) {
	resp, err := r.Upstream.Auth.RedeemLoginToken(ctx, &authv1.RedeemLoginTokenRequest{Token: token})
	if err != nil {
		return nil, err
	}
	return r.startSession(ctx, resp.GetUser())
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	if w, ok := auth.WriterFromContext(ctx); ok {
		r.Signer.ClearCookie(w)
	}
	return true, nil
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	// The caller is always White. A client-supplied id here would let anyone
	// start games as another user.
	id, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.Upstream.Game.CreateGame(ctx, &gamev1.CreateGameRequest{
		WhiteId:     id.UserID,
		BlackId:     deref(input.BlackID),
		EngineDepth: uint32(derefInt(input.EngineDepth)),
		InitialMs:   int64(derefInt(input.InitialMs)),
		IncrementMs: int64(derefInt(input.IncrementMs)),
		Rated:       input.Rated != nil && *input.Rated,
		VsEngine:    input.VsEngine != nil && *input.VsEngine,
	})
	if err != nil {
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, input model.MoveInput) (*model.Game, error) {
	// Identity comes from the session, never from the request body: otherwise a
	// spectator could move by naming a player's id.
	id, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.Upstream.Game.SubmitMove(ctx, &gamev1.SubmitMoveRequest{
		GameId:   input.GameID,
		Uci:      input.Uci,
		PlayerId: id.UserID,
	})
	if err != nil {
		return nil, err
	}
	g := toModelGame(resp.GetGame())
	r.publish(ctx, g)
	return g, nil
}

// Resign is the resolver for the resign field.
func (r *mutationResolver) Resign(ctx context.Context, input model.ResignInput) (*model.Game, error) {
	id, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.Upstream.Game.Resign(ctx, &gamev1.ResignRequest{
		GameId:   input.GameID,
		PlayerId: id.UserID,
	})
	if err != nil {
		return nil, err
	}
	g := toModelGame(resp.GetGame())
	r.publish(ctx, g)
	return g, nil
}

// JoinGame is the resolver for the joinGame field.
func (r *mutationResolver) JoinGame(ctx context.Context, gameID string) (*model.Game, error) {
	id, err := requireIdentity(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := r.Upstream.Game.JoinGame(ctx, &gamev1.JoinGameRequest{
		GameId:   gameID,
		PlayerId: id.UserID,
	})
	if err != nil {
		return nil, err
	}
	g := toModelGame(resp.GetGame())
	// Tell anyone already watching that the seat is filled and play can start.
	r.publish(ctx, g)
	return g, nil
}

// EnterQueue is the resolver for the enterQueue field.
func (r *mutationResolver) EnterQueue(ctx context.Context, input model.QueueInput) (*model.QueueTicket, error) {
	return r.enterQueue(ctx, input)
}

// LeaveQueue is the resolver for the leaveQueue field.
func (r *mutationResolver) LeaveQueue(ctx context.Context, input model.QueueInput) (bool, error) {
	return r.leaveQueue(ctx, input)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	id, err := auth.FromContext(ctx)
	if err != nil {
		return nil, nil // signed out is not an error
	}
	// Read through to the source: the JWT carries a name and guest flag captured
	// at sign-in, which go stale after a rename or a guest upgrade.
	resp, err := r.Upstream.Auth.GetUser(ctx, &authv1.GetUserRequest{UserId: id.UserID})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelUser(resp.GetUser()), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	resp, err := r.Upstream.Auth.GetUser(ctx, &authv1.GetUserRequest{UserId: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelUser(resp.GetUser()), nil
}

// GameHistory is the resolver for the gameHistory field.
func (r *queryResolver) GameHistory(ctx context.Context, userID *string, limit *int, offset *int) (*model.GameHistory, error) {
	target := deref(userID)
	if target == "" {
		id, err := requireIdentity(ctx)
		if err != nil {
			return nil, err
		}
		target = id.UserID
	}
	resp, err := r.Upstream.Game.ListGames(ctx, &gamev1.ListGamesRequest{
		UserId: target,
		Limit:  int32(derefInt(limit)),
		Offset: int32(derefInt(offset)),
	})
	if err != nil {
		return nil, err
	}
	games := make([]*model.GameSummary, 0, len(resp.GetGames()))
	for _, g := range resp.GetGames() {
		games = append(games, toModelSummary(g))
	}
	return &model.GameHistory{Games: games, Total: int(resp.GetTotal())}, nil
}

// Leaderboard is the resolver for the leaderboard field.
func (r *queryResolver) Leaderboard(ctx context.Context, limit *int) ([]*model.LeaderboardEntry, error) {
	resp, err := r.Upstream.Game.Leaderboard(ctx, &gamev1.LeaderboardRequest{
		Limit: int32(derefInt(limit)),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.LeaderboardEntry, 0, len(resp.GetEntries()))
	for _, e := range resp.GetEntries() {
		out = append(out, &model.LeaderboardEntry{
			Rank:        int(e.GetRank()),
			UserID:      e.GetUserId(),
			Username:    e.GetUsername(),
			Elo:         int(e.GetElo()),
			GamesPlayed: int(e.GetGamesPlayed()),
		})
	}
	return out, nil
}

// Game is the resolver for the game field. An unknown id resolves to null
// rather than an error, per GraphQL convention for nullable lookups.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	resp, err := r.Upstream.Game.GetGame(ctx, &gamev1.GetGameRequest{GameId: id})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelGame(resp.GetGame()), nil
}

// OpeningExplorer is the resolver for the openingExplorer field.
func (r *queryResolver) OpeningExplorer(ctx context.Context, fen *string, limit *int) (*model.OpeningExplorer, error) {
	resp, err := r.Upstream.Game.OpeningExplorer(ctx, &gamev1.OpeningExplorerRequest{
		Fen:   deref(fen),
		Limit: int32(derefInt(limit)),
	})
	if err != nil {
		return nil, err
	}
	moves := make([]*model.OpeningMove, 0, len(resp.GetMoves()))
	for _, m := range resp.GetMoves() {
		moves = append(moves, &model.OpeningMove{
			Uci: m.GetUci(), San: m.GetSan(),
			WhiteWins: int(m.GetWhiteWins()), BlackWins: int(m.GetBlackWins()),
			Draws: int(m.GetDraws()), Total: int(m.GetTotal()),
		})
	}
	return &model.OpeningExplorer{Moves: moves, TotalGames: int(resp.GetTotalGames())}, nil
}

// GamePgnURL is the resolver for the gamePgnUrl field.
func (r *queryResolver) GamePgnURL(ctx context.Context, gameID string) (*string, error) {
	resp, err := r.Upstream.Game.GamePgnUrl(ctx, &gamev1.GamePgnUrlRequest{GameId: gameID})
	if err != nil {
		return nil, err
	}
	if resp.GetUrl() == "" {
		return nil, nil // not archived yet
	}
	url := resp.GetUrl()
	return &url, nil
}

// GameAnalysis is the resolver for the gameAnalysis field.
func (r *queryResolver) GameAnalysis(ctx context.Context, gameID string) (*model.GameAnalysis, error) {
	resp, err := r.Upstream.Game.GetAnalysis(ctx, &gamev1.GetAnalysisRequest{GameId: gameID})
	if err != nil {
		// Not analysed yet is an ordinary state, not a failure: the pipeline is
		// asynchronous and the client renders this as "analysing…".
		if status.Code(err) == codes.NotFound {
			return nil, nil
		}
		return nil, err
	}
	return toModelAnalysis(resp), nil
}

// LegalMoves is the resolver for the legalMoves field.
func (r *queryResolver) LegalMoves(ctx context.Context, gameID string) ([]string, error) {
	resp, err := r.Upstream.Game.LegalMoves(ctx, &gamev1.LegalMovesRequest{GameId: gameID})
	if err != nil {
		return nil, err
	}
	// Never nil: the schema promises a list, and "no legal moves" (checkmate or
	// stalemate) is a legitimate empty answer, not an error.
	if resp.GetUci() == nil {
		return []string{}, nil
	}
	return resp.GetUci(), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// GameUpdated is the resolver for the gameUpdated field.
//
// Emits the game's current state immediately so a joining client renders a board
// straight away, then forwards every subsequent update published by the move and
// resign mutations. The channel closes when the client disconnects (ctx done).
func (r *subscriptionResolver) GameUpdated(ctx context.Context, gameID string) (<-chan *model.Game, error) {
	updates, err := r.Bus.Subscribe(ctx, gameID)
	if err != nil {
		return nil, err
	}

	// Fetch the current state before relaying, so a late joiner is not blank
	// until the next move. A missing game is a hard error here (unlike the
	// nullable `game` query): subscribing to nothing is a client mistake.
	current, err := r.Upstream.Game.GetGame(ctx, &gamev1.GetGameRequest{GameId: gameID})
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Game, 1)
	out <- toModelGame(current.GetGame())

	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case g, ok := <-updates:
				if !ok {
					return
				}
				select {
				case out <- g:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// MatchFound is the resolver for the matchFound field.
func (r *subscriptionResolver) MatchFound(ctx context.Context) (<-chan *model.Game, error) {
	return r.matchFound(ctx)
}

// Game returns generated.GameResolver implementation.
func (r *Resolver) Game() generated.GameResolver { return &gameResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	gameResolver         struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
